### ISSUE TITLE
loadBalancers crawl failing

### ISSUE THREAD

**Issue by hridyeshpant** [Netflix/edda#118]
latest change breaking loadBalancers crawl .
https://github.com/Netflix/edda/commit/c61ccf67a663bd2f1119c629903235389a1a7d8b

2017-02-26 14:06:00.895 - ERROR - [StateMachine.scala:204] [45300f82-d2cd-4b32-930e-f550d4cfe4b8 refresh]  failed to handle event Crawl([Collection us-east-1.aws.loadBalancers] refresher)
java.lang.ClassCastException: scala.collection.immutable.$colon$colon cannot be cast to com.netflix.edda.Record
	at com.netflix.edda.aws.AwsLoadBalancerCrawler$$anonfun$19.apply(AwsCrawlers.scala:370)
	at com.netflix.edda.aws.AwsLoadBalancerCrawler$$anonfun$19.apply(AwsCrawlers.scala:370)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$class.toStream(Iterator.scala:1322)
	at scala.collection.AbstractIterator.toStream(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.toSeq(TraversableOnce.scala:298)
	at scala.collection.AbstractIterator.toSeq(Iterator.scala:1336)
	at com.netflix.edda.aws.AwsLoadBalancerCrawler.doCrawl(AwsCrawlers.scala:370)
	at com.netflix.edda.aws.AwsLoadBalancerCrawler.doCrawl(AwsCrawlers.scala:352)
	at com.netflix.edda.Crawler$$anonfun$localTransitions$1.applyOrElse(Crawler.scala:132)
	at com.netflix.edda.Crawler$$anonfun$localTransitions$1.applyOrElse(Crawler.scala:119)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
	at com.netflix.edda.StateMachine$$anonfun$act$1$$anonfun$applyOrElse$2$$anonfun$apply$1.applyOrElse(StateMachine.scala:201)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at scala.actors.ReactorTask.run(ReactorTask.scala:31)
	at scala.actors.Reactor$class.resumeReceiver(Reactor.scala:130)
	at com.netflix.edda.StateMachine.scala$actors$InternalReplyReactor$$super$resumeReceiver(StateMachine.scala:100)
	at scala.actors.InternalReplyReactor$class.resumeReceiver(InternalReplyReactor.scala:60)
	at com.netflix.edda.StateMachine.resumeReceiver(StateMachine.scala:100)
	at scala.actors.InternalActor$class.searchMailbox(InternalActor.scala:76)
	at com.netflix.edda.StateMachine.searchMailbox(StateMachine.scala:100)
	at scala.actors.Reactor$$anonfun$startSearch$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(Reactor.scala:118)
	at scala.actors.Reactor$$anonfun$startSearch$1$$anonfun$apply$mcV$sp$1.apply(Reactor.scala:115)
	at scala.actors.Reactor$$anonfun$startSearch$1$$anonfun$apply$mcV$sp$1.apply(Reactor.scala:115)
	at scala.actors.ReactorTask.run(ReactorTask.scala:33)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by JazminGonzalez-Rivero** [comment]
has anyone started looking into this? I am also having this issue

**Comment by brharrington** [comment]
I haven't had time yet. The change causing it hasn't been released yet, so you should be able to use [2.3.0](https://github.com/Netflix/edda/releases/tag/v2.3.0).
